from __future__ import annotations

import secrets
from pathlib import Path

import pandas as pd
import streamlit as st

from runbeat.planner import WORKOUTS, infer_cadence, personalize_plan
from runbeat.selector import select_tracks
from runbeat.spotify import (
    authorization_url,
    create_pkce_pair,
    create_playlist,
    current_user,
    exchange_code,
    replace_playlist_items,
)

st.set_page_config(page_title="RunBeat Coach", page_icon="🏃", layout="wide")
st.title("🏃 RunBeat Coach")
st.caption("Turn your latest run into a BPM-shaped Spotify playlist for the next workout.")

DATA_PATH = Path("data/song_catalog.csv")


def load_catalog() -> pd.DataFrame:
    return pd.read_csv(DATA_PATH)


def handle_spotify_callback() -> None:
    code = st.query_params.get("code")
    state = st.query_params.get("state")
    if not code or "spotify_token" in st.session_state:
        return
    if state != st.session_state.get("oauth_state"):
        st.error("Spotify login state did not match. Please reconnect.")
        return
    try:
        token = exchange_code(
            st.secrets["SPOTIFY_CLIENT_ID"],
            st.secrets["SPOTIFY_REDIRECT_URI"],
            code,
            st.session_state["pkce_verifier"],
        )
        st.session_state["spotify_token"] = token["access_token"]
        st.query_params.clear()
        st.rerun()
    except Exception as exc:
        st.error(f"Spotify authorization failed: {exc}")


with st.sidebar:
    st.header("Spotify")
    spotify_configured = "SPOTIFY_CLIENT_ID" in st.secrets and "SPOTIFY_REDIRECT_URI" in st.secrets
    if spotify_configured:
        handle_spotify_callback()
        if "spotify_token" not in st.session_state:
            if "pkce_verifier" not in st.session_state:
                verifier, challenge = create_pkce_pair()
                st.session_state["pkce_verifier"] = verifier
                st.session_state["pkce_challenge"] = challenge
                st.session_state["oauth_state"] = secrets.token_urlsafe(24)
            login_url = authorization_url(
                st.secrets["SPOTIFY_CLIENT_ID"],
                st.secrets["SPOTIFY_REDIRECT_URI"],
                st.session_state["pkce_challenge"],
                st.session_state["oauth_state"],
            )
            st.link_button("Connect Spotify", login_url, use_container_width=True)
        else:
            st.success("Spotify connected")
    else:
        st.info("Copy `.streamlit/secrets.toml.example` to `.streamlit/secrets.toml` and add your Spotify Client ID.")

st.subheader("1. Upload your latest run")
run_file = st.file_uploader("Run CSV", type=["csv"], help="Cadence columns can be named cadence, avg_cadence, or spm.")
if run_file:
    run_df = pd.read_csv(run_file)
    st.dataframe(run_df.head(20), use_container_width=True)
else:
    run_df = pd.DataFrame([{"distance_miles": 3.5, "pace": "9:07", "cadence": 160}])
    st.caption("Using a 160 SPM demo run until you upload a CSV.")

observed_cadence = infer_cadence(run_df)

st.subheader("2. Choose the next workout")
left, middle, right = st.columns(3)
with left:
    workout_name = st.selectbox("Workout", list(WORKOUTS))
with middle:
    duration = st.slider("Minutes", 20, 90, WORKOUTS[workout_name].duration_minutes, 5)
with right:
    tolerance = st.slider("BPM tolerance", 1, 10, 5)

base_plan = WORKOUTS[workout_name]
base_plan = base_plan.__class__(
    base_plan.name, duration, base_plan.start_bpm, base_plan.middle_bpm, base_plan.finish_bpm, base_plan.description
)
plan = personalize_plan(base_plan, observed_cadence)

st.info(
    f"Observed cadence: **{observed_cadence} SPM** · Playlist arc: "
    f"**{plan.start_bpm} → {plan.middle_bpm} → {plan.finish_bpm} BPM**"
)

st.subheader("3. Review the generated playlist")
catalog = load_catalog()
playlist = select_tracks(catalog, plan, tolerance=tolerance)
if playlist.empty:
    st.warning("Add songs to `data/song_catalog.csv` before generating a playlist.")
else:
    display_columns = ["position", "track_name", "artist", "effective_bpm", "target_bpm", "bpm_delta"]
    st.dataframe(playlist[display_columns], hide_index=True, use_container_width=True)
    total_minutes = playlist["duration_ms"].sum() / 60_000
    st.caption(f"{len(playlist)} tracks · approximately {total_minutes:.1f} minutes")

    playlist_name = st.text_input("Spotify playlist name", f"RunBeat · {plan.name} · {plan.start_bpm}-{plan.finish_bpm} BPM")
    if st.button("Create Spotify playlist", type="primary", disabled="spotify_token" not in st.session_state):
        try:
            token = st.session_state["spotify_token"]
            profile = current_user(token)
            created = create_playlist(
                token,
                playlist_name,
                f"Generated by RunBeat Coach from an observed cadence of {observed_cadence} SPM.",
            )
            replace_playlist_items(token, created["id"], playlist["spotify_uri"].tolist())
            st.success("Playlist created in Spotify.")
            if created.get("external_urls", {}).get("spotify"):
                st.link_button("Open playlist", created["external_urls"]["spotify"])
        except Exception as exc:
            st.error(f"Could not create playlist: {exc}")

with st.expander("Song catalog format"):
    st.code("track_name,artist,spotify_uri,effective_bpm,duration_ms,rating,recently_used", language="text")
    st.write("`effective_bpm` may be the song's literal BPM or its useful double-time running BPM.")
